#finetune
finetune: True
scores_lambda: 0.0001

# Architecture
arch: cResNet18 

# ===== Dataset ===== #
data: /mnt/disk1/datasets
set: CIFAR10
name: baseline

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.1
lr_policy: cosine_lr

# ===== Network training config ===== #
epochs: 150
weight_decay: 0.0005
momentum: 0.9
batch_size: 256
exp_custom_exponents: 1
# ===== Sparsity =========== #
conv_type: SubnetConv
bn_type: NonAffineBatchNorm
init: signed_constant
freeze_weights: True
mode: fan_in
nonlinearity: relu
prune_rate: -1

# ===== Hardware setup ===== #
workers: 48